name: ISO10383

# TODO: Setup a schedule to update when ISO20022 updates the csv.
on:
  pull_request:
    branches:
      - main

concurrency:
  group: iso10383
  cancel-in-progress: true

jobs:
  # install:
  #   name: Install dependencies
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Download dependencies
  #       uses: bahmutov/npm-install@v1

  update-csv:
    name: Update CSV
    runs-on: ubuntu-latest
    # needs:
    #   - install
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      # - name: Download dependencies
      #   uses: bahmutov/npm-install@v1

      - name: Download CSV
        env:
          CI_COMMIT_MESSAGE: Update ISO10383 specifications
          CI_COMMIT_AUTHOR: 📈 ISO10383 Bot
          CSV_PATH: packages/iso-10383/src/specifications/iso10383.csv
        run: |
          curl -o "${{ env.CSV_PATH }}" https://www.iso20022.org/sites/default/files/ISO10383_MIC/ISO10383_MIC.csv
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git add "${{ env.CSV_PATH }}"
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push

# TODO: Add generator
# TODO: Generate typescript files
# TODO: Export specifications
# TODO: Create a changeset
