name: Run tests on PR

on:
  pull_request:
    branches:
      - main

# Cancel previously running workflows
concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download dependencies
        uses: bahmutov/npm-install@v1

  lint:
    name: Run linting
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download dependencies
        uses: bahmutov/npm-install@v1

      - name: Run tests and linting
        run: npm run lint-all

  test:
    name: Run tests
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download dependencies
        uses: bahmutov/npm-install@v1

      - name: Run tests and linting
        run: npm run test-all
