name: Release

on:
  push:
    branches:
      - main

# Cancel previously running workflows
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download dependencies
        uses: bahmutov/npm-install@v1

  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download dependencies
        uses: bahmutov/npm-install@v1

      - name: Run tests
        run: npm run test-all

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download dependencies
        uses: bahmutov/npm-install@v1

      - name: Run linting
        run: npm run lint-all
